
'use client';

import { AppLayout } from '@/components/layout/AppLayout';
// APP_NAV_CONFIG is no longer passed as a prop
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Leaf, Loader2 } from 'lucide-react';
import { useState, useEffect } from 'react';
import { useParams, useRouter, notFound } from 'next/navigation';
import { mockPlants } from '@/lib/mock-data';
import type { Plant, PlantFormData } from '@/types';
import { useToast } from '@/hooks/use-toast';
import { SavePlantForm } from '@/components/plants/SavePlantForm'; 

export default function EditPlantPage() {
  const router = useRouter();
  const params = useParams();
  const id = params.id as string;
  const { toast } = useToast();

  const [plant, setPlant] = useState<Plant | null>(null);
  const [initialFormData, setInitialFormData] = useState<Partial<PlantFormData> | undefined>(undefined);
  const [isLoadingPage, setIsLoadingPage] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    if (id) {
      const foundPlant = mockPlants.find(p => p.id === id);
      if (foundPlant) {
        setPlant(foundPlant);
        
        let ageYears: number | undefined = undefined;
        if (foundPlant.ageEstimate) {
          const match = foundPlant.ageEstimate.match(/(\d+(\.\d+)?)/);
          if (match && match[1]) {
            ageYears = parseFloat(match[1]);
          }
        }

        setInitialFormData({
          commonName: foundPlant.commonName,
          scientificName: foundPlant.scientificName || '',
          familyCategory: foundPlant.familyCategory || '',
          ageEstimateYears: ageYears,
          healthCondition: foundPlant.healthCondition,
          location: foundPlant.location || '',
          customNotes: foundPlant.customNotes || '',
          diagnosedPhotoDataUrl: foundPlant.primaryPhotoUrl || null,
        });
      } else {
        notFound();
      }
    }
    setIsLoadingPage(false);
  }, [id]);

  const handleUpdatePlant = async (data: PlantFormData) => {
    setIsSaving(true);
    // Simulate API call to update the plant
    await new Promise(resolve => setTimeout(resolve, 1500));

    const plantIndex = mockPlants.findIndex(p => p.id === id);
    if (plantIndex !== -1 && plant) {
        // Mock update:
        // In a real app, you'd get a new URL from S3/backend if a new photo was uploaded
        let updatedPhotoUrl = data.diagnosedPhotoDataUrl; // This would be the new data URL if user changed photo in form

        if (data.primaryPhoto && data.primaryPhoto[0]) {
          // If a new file is in primaryPhoto, it means user uploaded a new one
          // For mock, we'll just use the dataURL generated by SavePlantForm's preview logic
          // The form itself sets `diagnosedPhotoDataUrl` to the preview of `primaryPhoto`
          // So, data.diagnosedPhotoDataUrl should reflect the new image if one was selected.
        } else {
          // No new file uploaded, keep existing primaryPhotoUrl
          updatedPhotoUrl = plant.primaryPhotoUrl;
        }
        
        mockPlants[plantIndex] = {
          ...mockPlants[plantIndex],
          commonName: data.commonName,
          scientificName: data.scientificName || undefined,
          familyCategory: data.familyCategory || '', // Ensure it's always a string
          ageEstimate: data.ageEstimateYears ? `${data.ageEstimateYears} years` : undefined,
          healthCondition: data.healthCondition,
          location: data.location || undefined,
          customNotes: data.customNotes || undefined,
          primaryPhotoUrl: updatedPhotoUrl || plant.primaryPhotoUrl, // Fallback if something went wrong
        };
        // Update photos array - if primaryPhotoUrl changed, update the first photo or add it
        if (updatedPhotoUrl && (!mockPlants[plantIndex].photos.length || mockPlants[plantIndex].photos[0].url !== updatedPhotoUrl) ) {
          const newMainPhotoEntry = {
            id: mockPlants[plantIndex].photos[0]?.id || `p-${id}-initial-${Date.now()}`,
            url: updatedPhotoUrl,
            dateTaken: mockPlants[plantIndex].photos[0]?.dateTaken || new Date().toISOString(),
            healthCondition: data.healthCondition, // Reflect current health
            diagnosisNotes: "Updated via edit form."
          };
          if (mockPlants[plantIndex].photos.length > 0) {
            mockPlants[plantIndex].photos[0] = newMainPhotoEntry;
          } else {
            mockPlants[plantIndex].photos.push(newMainPhotoEntry);
          }
        }

        toast({
          title: 'Plant Updated!',
          description: `${data.commonName} has been (simulated) updated.`,
        });
    } else {
      toast({
        title: 'Error',
        description: 'Could not find plant to update.',
        variant: 'destructive'
      });
    }
    
    setIsSaving(false);
    router.push(`/plants/${id}`); 
  };

  if (isLoadingPage || !initialFormData) {
    return (
      <AppLayout> {/* navItemsConfig prop removed */}
        <div className="flex justify-center items-center h-full">
          <Loader2 className="h-12 w-12 animate-spin text-primary" />
        </div>
      </AppLayout>
    );
  }

  if (!plant) { 
    return notFound();
  }

  return (
    <AppLayout> {/* navItemsConfig prop removed */}
      <div className="max-w-2xl mx-auto">
        <SavePlantForm
          initialData={initialFormData}
          onSave={handleUpdatePlant}
          onCancel={() => router.push(`/plants/${id}`)}
          isLoading={isSaving}
          formTitle="Edit Plant"
          formDescription={`Update the details for ${plant.commonName}.`}
          submitButtonText="Update Plant"
        />
      </div>
    </AppLayout>
  );
}
